apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
      - name: go-app
        image:  khmndr/restapis:tagname  # Ensure this image is built and pushed
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          value: "postgres-service:5433"  # Updated to reflect the exposed port
        - name: DB_USER
          value: "postgres"
        - name: DB_PASS
          value: "postgres123"
        - name: DB_NAME
          value: "mydatabase"
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"


---


apiVersion: v1
kind: Service
metadata:
  name: my-go-app-service
spec:
  selector:
    app: my-go-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort


